import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "../modules/navbar";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${figtree.className} antialiased`}>
      <body className="leading-[1.5] min-h-screen mx-auto">
        <header className="max-w-prose shadow z-50 bg-white mx-auto mb-4">
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
